//
//  MessagesInteractor.swift
//  safe
//
//  Created by Daniel on 8/10/19.
//  Copyright (c) 2019 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MessagesBusinessLogic {
  /// Tells interactor that user send a new image
  func sendImage(request: Messages.newImage.Request)
}

protocol MessagesDataStore {
  //var name: String { get set }
}

class MessagesInteractor: MessagesBusinessLogic, MessagesDataStore {

  var presenter: MessagesPresentationLogic?
  var worker: MessagesWorker?

  func sendImage(request: Messages.newImage.Request) {
    // TODO: [Repleace when exist incoming message].
    presenter?.presentNewImage(response: Messages.newImage.Response(image: request.image, name: "Daniel", isUser: true))
  }
}
