//
//  MessagesInteractor.swift
//  safe
//
//  Created by Daniel on 8/10/19.
//  Copyright (c) 2019 Daniel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MessagesBusinessLogic {
  func doSomething(request: Messages.Something.Request)
  /// Tells interactor that user pressed gallery buttons
  func sendImage(request: Messages.SendImage.Request)
}

protocol MessagesDataStore {
  //var name: String { get set }
}

class MessagesInteractor: MessagesBusinessLogic, MessagesDataStore {

  var presenter: MessagesPresentationLogic?
  var worker: MessagesWorker?

  // MARK: Do something
  func doSomething(request: Messages.Something.Request) {
    worker = MessagesWorker()
    worker?.doSomeWork()
    
    let response = Messages.Something.Response()
    presenter?.presentSomething(response: response)
  }

  func sendImage(request: Messages.SendImage.Request) {

  }
}
